<a href="https://colab.research.google.com/github/aryansinghchauhan/ml-models/blob/main/loan_repay_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv('/content/train_u6lujuX_CVtuZ9i (1).csv')

In [4]:
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [5]:
df1=df.drop(['Loan_ID'],axis=1)

In [6]:
df1.head()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [8]:
df1.shape

(614, 12)

In [9]:
df1['Gender'].value_counts()

Gender
Male      489
Female    112
Name: count, dtype: int64

In [10]:
df1.replace({'Gender':{'Male':1,'Female':0}})

<ipython-input-10-20ba9161d2d9>:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1.replace({'Gender':{'Male':1,'Female':0}})

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,1.0,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,1.0,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,1.0,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,1.0,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,1.0,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...
609,0.0,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,1.0,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,1.0,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,1.0,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,0.0,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [11]:
df1.shape

(614, 12)

In [12]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Gender             601 non-null    object
 1   Married            611 non-null    object
 2   Dependents         599 non-null    object
 3   Education          614 non-null    object
 4   Self_Employed      582 non-null    object
 5   ApplicantIncome    614 non-null    int64
 6   CoapplicantIncome  614 non-null    float64
 7   LoanAmount         592 non-null    float64
 8   Loan_Amount_Term   600 non-null    float64
 9   Credit_History     564 non-null    float64
 10  Property_Area      614 non-null    object
 11  Loan_Status        614 non-null    object
dtypes: float64(4), int64(1), object(7)
memory usage: 57.7+ KB

In [13]:
df1.isnull().sum()

Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [14]:
df1['Gender'].fillna  (df1['Gender'].mode()[0],inplace=True)

<ipython-input-14-92410ba8b747>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1['Gender'].fillna  (df1['Gender'].mode()[0],inplace=True)

In [15]:
df1.isnull().sum()

Gender                0
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [16]:
df1['Married'].fillna(df1['Married'].mode()[0],inplace=True)

<ipython-input-16-a154df153823>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1['Married'].fillna(df1['Married'].mode()[0],inplace=True)

In [22]:
df1.dropna(inplace=True)

In [23]:
df1.head()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
1,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
5,Male,Yes,2,Graduate,Yes,5417,4196.0,267.0,360.0,1.0,Urban,Y

In [24]:
df1['CoapplicantIncome'].value_counts()

CoapplicantIncome
0.0       222
1666.0      5
2500.0      4
5625.0      3
2083.0      3
         ...
3300.0      1
1000.0      1
4301.0      1
1411.0      1
240.0       1
Name: count, Length: 235, dtype: int64

In [97]:
df1.ApplicantIncome.value_counts()
p=df1.drop(['Dependents'],axis=1)

In [98]:
from sklearn.preprocessing import LabelEncoder

In [99]:
from sklearn.preprocessing import MaxAbsScaler

In [100]:
from sklearn.preprocessing import StandardScaler

In [101]:
from sklearn.preprocessing import OneHotEncoder

In [102]:
from sklearn.compose import ColumnTransformer

In [103]:
transformer=ColumnTransformer(transformers=[('tnf1',StandardScaler(),['ApplicantIncome','LoanAmount','Loan_Amount_Term']),
                                             ('tnf2',OneHotEncoder(sparse_output=False,drop='first'),['Gender','Married','Education','Property_Area','Self_Employed']),
                                             ('tnf3',MaxAbsScaler(),['CoapplicantIncome'])],remainder='passthrough')

In [104]:
x1=p.drop(['Loan_Status'],axis=1)

In [105]:
y=df1['Loan_Status']

In [115]:
x_trf7=transformer.fit_transform(x1)

In [116]:

le=LabelEncoder()

In [117]:
x_trf7.shape

(492, 11)

In [118]:
y_trf1=le.fit_transform(y)

In [119]:
from sklearn.model_selection import train_test_split

In [120]:
x_train,x_test,y_train,y_test=train_test_split(x_trf7,y_trf1,test_size=0.2,random_state=0)

In [121]:
from sklearn import svm

In [122]:
s=svm.SVC()

In [123]:
s.fit(x_train,y_train)

SVC()

In [65]:
df1.shape

(492, 12)

In [66]:
df1.isnull().sum()

Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [96]:
df1.Dependents.value_counts()

Dependents
0     280
2      87
1      81
3+     44
Name: count, dtype: int64

In [124]:
y_pred=s.predict(x_test)

In [126]:
from sklearn.metrics import accuracy_score

In [127]:
accuracy_score(y_test,y_pred)

0.8181818181818182